In [43]:
import pandas as pd 
import numpy as np
pd.options.display.max_rows=100
df = pd.read_csv("D:/absenteeism_project/Absenteeism_data.csv")
df.sample(10)

ID  Reason for Absence        Date  Transportation Expense  \
332  24                  13  21/11/2016                     246   
28   11                  18  19/08/2015                     289   
694  15                  22  23/05/2018                     291   
276   8                   0  13/09/2016                     231   
549  11                   0  29/11/2017                     289   
456  22                  21  28/06/2017                     179   
100  36                  23  02/12/2015                     118   
41   34                  23  07/09/2015                     118   
27   30                  28  12/08/2015                     157   
72    3                  23  21/10/2015                     179   

     Distance to Work  Age  Daily Work Load Average  Body Mass Index  \
332                25   41                  284.031               23   
28                 36   33                  205.917               30   
694                31   40                  237.656               25   
276                35   39                  294.217               35   
549                36   33                  268.519               30   
456                26   30                  253.957               19   
100                13   50                  261.306               31   
41                 10   37                  241.476               28   
27                 27   29                  205.917               22   
72                 51   38                  253.465               31   

     Education  Children  Pets  Absenteeism Time in Hours  
332          1         0     0                          8  
28           1         2     1                          8  
694          1         1     1                          8  
276          1         2     2                          0  
549          1         2     1                          0  
456          3         0     0                          2  
100          1         1     0                          2  
41           1         0     0                          4  
27           1         0     0                          4  
72           1         0     0                          8

In [44]:
data = df.drop("ID",axis=1)
data.sample(10)

Reason for Absence        Date  Transportation Expense  Distance to Work  \
245                  25  18/07/2016                     157                27   
661                  16  10/04/2018                     179                22   
595                  27  12/02/2018                     179                51   
573                  25  05/01/2018                     179                22   
547                  23  28/11/2017                     225                26   
413                  28  07/04/2017                     260                50   
613                  23  27/02/2018                     248                25   
321                  23  14/11/2016                     291                31   
277                   0  13/09/2016                     291                50   
291                  26  05/10/2016                     289                36   

     Age  Daily Work Load Average  Body Mass Index  Education  Children  Pets  \
245   29                  275.312               22          1         0     0   
661   40                  246.288               22          2         2     0   
595   38                  264.249               31          1         0     0   
573   40                  313.532               22          2         2     0   
547   28                  268.519               24          1         1     2   
413   36                  239.409               23          1         4     0   
613   47                  264.249               32          1         2     1   
321   40                  284.031               25          1         1     1   
277   32                  294.217               23          1         0     0   
291   33                  265.017               30          1         2     1   

     Absenteeism Time in Hours  
245                          3  
661                          2  
595                          2  
573                          2  
547                          2  
413                          3  
613                          2  
321                          1  
277                          0  
291                          8

In [45]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 700 entries, 0 to 699
Data columns (total 11 columns):
 #   Column                     Non-Null Count  Dtype  
---  ------                     --------------  -----  
 0   Reason for Absence         700 non-null    int64  
 1   Date                       700 non-null    object 
 2   Transportation Expense     700 non-null    int64  
 3   Distance to Work           700 non-null    int64  
 4   Age                        700 non-null    int64  
 5   Daily Work Load Average    700 non-null    float64
 6   Body Mass Index            700 non-null    int64  
 7   Education                  700 non-null    int64  
 8   Children                   700 non-null    int64  
 9   Pets                       700 non-null    int64  
 10  Absenteeism Time in Hours  700 non-null    int64  
dtypes: float64(1), int64(9), object(1)
memory usage: 60.3+ KB


In [46]:
data.describe()

Reason for Absence  Transportation Expense  Distance to Work  \
count          700.000000              700.000000        700.000000   
mean            19.411429              222.347143         29.892857   
std              8.356292               66.312960         14.804446   
min              0.000000              118.000000          5.000000   
25%             13.000000              179.000000         16.000000   
50%             23.000000              225.000000         26.000000   
75%             27.000000              260.000000         50.000000   
max             28.000000              388.000000         52.000000   

              Age  Daily Work Load Average  Body Mass Index   Education  \
count  700.000000               700.000000       700.000000  700.000000   
mean    36.417143               271.801774        26.737143    1.282857   
std      6.379083                40.021804         4.254701    0.668090   
min     27.000000               205.917000        19.000000    1.000000   
25%     31.000000               241.476000        24.000000    1.000000   
50%     37.000000               264.249000        25.000000    1.000000   
75%     40.000000               294.217000        31.000000    1.000000   
max     58.000000               378.884000        38.000000    4.000000   

         Children        Pets  Absenteeism Time in Hours  
count  700.000000  700.000000                 700.000000  
mean     1.021429    0.687143                   6.761429  
std      1.112215    1.166095                  12.670082  
min      0.000000    0.000000                   0.000000  
25%      0.000000    0.000000                   2.000000  
50%      1.000000    0.000000                   3.000000  
75%      2.000000    1.000000                   8.000000  
max      4.000000    8.000000                 120.000000

In [47]:
min(data["Reason for Absence"])

0

In [48]:
max(data["Reason for Absence"])

28

In [49]:
len(data["Reason for Absence"].unique())

28

In [50]:
sorted(data["Reason for Absence"].unique())

[0,
 1,
 2,
 3,
 4,
 5,
 6,
 7,
 8,
 9,
 10,
 11,
 12,
 13,
 14,
 15,
 16,
 17,
 18,
 19,
 21,
 22,
 23,
 24,
 25,
 26,
 27,
 28]

In [51]:
reasons_for_absence = pd.get_dummies(data["Reason for Absence"],dtype='int32',drop_first=True)

In [52]:
reasons_for_absence["check"] = reasons_for_absence.sum(axis=1)
reasons_for_absence.head()

1  2  3  4  5  6  7  8  9  10  ...  19  21  22  23  24  25  26  27  28  \
0  0  0  0  0  0  0  0  0  0   0  ...   0   0   0   0   0   0   1   0   0   
1  0  0  0  0  0  0  0  0  0   0  ...   0   0   0   0   0   0   0   0   0   
2  0  0  0  0  0  0  0  0  0   0  ...   0   0   0   1   0   0   0   0   0   
3  0  0  0  0  0  0  1  0  0   0  ...   0   0   0   0   0   0   0   0   0   
4  0  0  0  0  0  0  0  0  0   0  ...   0   0   0   1   0   0   0   0   0   

   check  
0      1  
1      0  
2      1  
3      1  
4      1  

[5 rows x 28 columns]

In [53]:
reasons_for_absence.check.unique()

array([1, 0], dtype=int64)

In [54]:
reasons_for_absence.drop("check",axis=1,inplace=True)

In [55]:
reason_dummies = reasons_for_absence.copy()
age_dummies = pd.get_dummies(data["Age"],dtype="int32",drop_first=True)

In [56]:
age_dummies.head()

28  29  30  31  32  33  34  36  37  38  39  40  41  43  46  47  48  49  50  \
0   0   0   0   0   0   1   0   0   0   0   0   0   0   0   0   0   0   0   0   
1   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   1   
2   0   0   0   0   0   0   0   0   0   1   0   0   0   0   0   0   0   0   0   
3   0   0   0   0   0   0   0   0   0   0   1   0   0   0   0   0   0   0   0   
4   0   0   0   0   0   1   0   0   0   0   0   0   0   0   0   0   0   0   0   

   58  
0   0  
1   0  
2   0  
3   0  
4   0

In [57]:
reason_dummies.columns.values

array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19,
       21, 22, 23, 24, 25, 26, 27, 28], dtype=object)

In [58]:
data.drop(["Reason for Absence"],axis=1,inplace=True)

In [59]:
reason_type_1=reason_dummies.loc[:,1:14].max(axis=1)
reason_type_2=reason_dummies.loc[:,15:17].max(axis=1)
reason_type_3=reason_dummies.loc[:,18:21].max(axis=1)
reason_type_4=reason_dummies.loc[:,22:].max(axis=1)

In [60]:
reason_type_1

0      0
1      0
2      0
3      1
4      0
      ..
695    1
696    1
697    1
698    0
699    0
Length: 700, dtype: int32

In [61]:
reason_type_2

0      0
1      0
2      0
3      0
4      0
      ..
695    0
696    0
697    0
698    0
699    0
Length: 700, dtype: int32

In [62]:
data = pd.concat([data,reason_type_1,reason_type_2,reason_type_3,reason_type_4],axis=1)

In [63]:
data.head()

Date  Transportation Expense  Distance to Work  Age  \
0  07/07/2015                     289                36   33   
1  14/07/2015                     118                13   50   
2  15/07/2015                     179                51   38   
3  16/07/2015                     279                 5   39   
4  23/07/2015                     289                36   33   

   Daily Work Load Average  Body Mass Index  Education  Children  Pets  \
0                  239.554               30          1         2     1   
1                  239.554               31          1         1     0   
2                  239.554               31          1         0     0   
3                  239.554               24          1         2     0   
4                  239.554               30          1         2     1   

   Absenteeism Time in Hours  0  1  2  3  
0                          4  0  0  0  1  
1                          0  0  0  0  0  
2                          2  0  0  0  1  
3                          4  1  0  0  0  
4                          2  0  0  0  1

In [64]:
data.columns.values

array(['Date', 'Transportation Expense', 'Distance to Work', 'Age',
       'Daily Work Load Average', 'Body Mass Index', 'Education',
       'Children', 'Pets', 'Absenteeism Time in Hours', 0, 1, 2, 3],
      dtype=object)

In [65]:
columns_names = ['Date', 'Transportation Expense', 'Distance to Work', 'Age',
       'Daily Work Load Average', 'Body Mass Index', 'Education',
       'Children', 'Pets', 'Absenteeism Time in Hours', 'reason_type_1', 'reason_type_2', 'reason_type_3', 'reason_type_4']

data.columns = columns_names

In [66]:
data.head()

Date  Transportation Expense  Distance to Work  Age  \
0  07/07/2015                     289                36   33   
1  14/07/2015                     118                13   50   
2  15/07/2015                     179                51   38   
3  16/07/2015                     279                 5   39   
4  23/07/2015                     289                36   33   

   Daily Work Load Average  Body Mass Index  Education  Children  Pets  \
0                  239.554               30          1         2     1   
1                  239.554               31          1         1     0   
2                  239.554               31          1         0     0   
3                  239.554               24          1         2     0   
4                  239.554               30          1         2     1   

   Absenteeism Time in Hours  reason_type_1  reason_type_2  reason_type_3  \
0                          4              0              0              0   
1                          0              0              0              0   
2                          2              0              0              0   
3                          4              1              0              0   
4                          2              0              0              0   

   reason_type_4  
0              1  
1              0  
2              1  
3              0  
4              1

In [67]:
age_dummies.head()

28  29  30  31  32  33  34  36  37  38  39  40  41  43  46  47  48  49  50  \
0   0   0   0   0   0   1   0   0   0   0   0   0   0   0   0   0   0   0   0   
1   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   1   
2   0   0   0   0   0   0   0   0   0   1   0   0   0   0   0   0   0   0   0   
3   0   0   0   0   0   0   0   0   0   0   1   0   0   0   0   0   0   0   0   
4   0   0   0   0   0   1   0   0   0   0   0   0   0   0   0   0   0   0   0   

   58  
0   0  
1   0  
2   0  
3   0  
4   0

In [68]:
data['Date'] = pd.to_datetime(data['Date'],dayfirst=True)

In [69]:
data['Date']

0     2015-07-07
1     2015-07-14
2     2015-07-15
3     2015-07-16
4     2015-07-23
         ...    
695   2018-05-23
696   2018-05-23
697   2018-05-24
698   2018-05-24
699   2018-05-31
Name: Date, Length: 700, dtype: datetime64[ns]

In [70]:
data['Date'][0]

Timestamp('2015-07-07 00:00:00')

In [71]:
data['Date'][0].month

7

In [72]:
list_months = []
for i in range(data.shape[0]):
    list_months.append(data['Date'][i].month)

In [73]:
len(list_months)

700

In [74]:
data["Month Values"] = list_months

In [75]:
data.head()

Date  Transportation Expense  Distance to Work  Age  \
0 2015-07-07                     289                36   33   
1 2015-07-14                     118                13   50   
2 2015-07-15                     179                51   38   
3 2015-07-16                     279                 5   39   
4 2015-07-23                     289                36   33   

   Daily Work Load Average  Body Mass Index  Education  Children  Pets  \
0                  239.554               30          1         2     1   
1                  239.554               31          1         1     0   
2                  239.554               31          1         0     0   
3                  239.554               24          1         2     0   
4                  239.554               30          1         2     1   

   Absenteeism Time in Hours  reason_type_1  reason_type_2  reason_type_3  \
0                          4              0              0              0   
1                          0              0              0              0   
2                          2              0              0              0   
3                          4              1              0              0   
4                          2              0              0              0   

   reason_type_4  Month Values  
0              1             7  
1              0             7  
2              1             7  
3              0             7  
4              1             7

In [76]:
def weekofday(date_value):
    return date_value.weekday()

In [77]:
data["Week of Day"] = data["Date"].apply(weekofday)
data.head()

Date  Transportation Expense  Distance to Work  Age  \
0 2015-07-07                     289                36   33   
1 2015-07-14                     118                13   50   
2 2015-07-15                     179                51   38   
3 2015-07-16                     279                 5   39   
4 2015-07-23                     289                36   33   

   Daily Work Load Average  Body Mass Index  Education  Children  Pets  \
0                  239.554               30          1         2     1   
1                  239.554               31          1         1     0   
2                  239.554               31          1         0     0   
3                  239.554               24          1         2     0   
4                  239.554               30          1         2     1   

   Absenteeism Time in Hours  reason_type_1  reason_type_2  reason_type_3  \
0                          4              0              0              0   
1                          0              0              0              0   
2                          2              0              0              0   
3                          4              1              0              0   
4                          2              0              0              0   

   reason_type_4  Month Values  Week of Day  
0              1             7            1  
1              0             7            1  
2              1             7            2  
3              0             7            3  
4              1             7            3

In [78]:
data_date_mod = data.copy()
data_date_mod.drop("Date",axis=1,inplace=True)

In [79]:
data_date_mod.head()

Transportation Expense  Distance to Work  Age  Daily Work Load Average  \
0                     289                36   33                  239.554   
1                     118                13   50                  239.554   
2                     179                51   38                  239.554   
3                     279                 5   39                  239.554   
4                     289                36   33                  239.554   

   Body Mass Index  Education  Children  Pets  Absenteeism Time in Hours  \
0               30          1         2     1                          4   
1               31          1         1     0                          0   
2               31          1         0     0                          2   
3               24          1         2     0                          4   
4               30          1         2     1                          2   

   reason_type_1  reason_type_2  reason_type_3  reason_type_4  Month Values  \
0              0              0              0              1             7   
1              0              0              0              0             7   
2              0              0              0              1             7   
3              1              0              0              0             7   
4              0              0              0              1             7   

   Week of Day  
0            1  
1            1  
2            2  
3            3  
4            3

In [80]:
data_date_mod["Education"].unique()

array([1, 3, 2, 4], dtype=int64)

In [81]:
data_date_mod["Education"] = data_date_mod["Education"].map({1:0,2:1,3:1,4:1})
data_date_mod["Education"].unique()

array([0, 1], dtype=int64)

In [82]:
data_date_mod.to_csv("Absenteeism_prprocessed.csv",index=False)